services:
  db:
    image: postgres:15-alpine
    container_name: postgres_trading
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: testtrading
      POSTGRES_DB: trading_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: